"""Behaviour-changing mutations of a claimed source region.

Every operator here changes what the code *does*, not how it reads. That is the
whole point: if the claimed region can behave differently and the check stays
green, the check is not reading the behaviour it claims to verify.

Mutants are generated by rewriting the module's AST and unparsing it, so a
mutant is always syntactically valid Python -- a mutant that merely fails to
parse would be "killed" by every check, including a vacuous one, and would
inflate the kill rate for free.
"""

from __future__ import annotations

import ast
import dataclasses
from pathlib import Path

_CMP_FLIP = {
    ast.Eq: ast.NotEq, ast.NotEq: ast.Eq,
    ast.Lt: ast.GtE, ast.GtE: ast.Lt,
    ast.Gt: ast.LtE, ast.LtE: ast.Gt,
    ast.Is: ast.IsNot, ast.IsNot: ast.Is,
    ast.In: ast.NotIn, ast.NotIn: ast.In,
}
_BINOP_SWAP = {
    ast.Add: ast.Sub, ast.Sub: ast.Add,
    ast.Mult: ast.FloorDiv, ast.FloorDiv: ast.Mult,
    ast.Div: ast.Mult,
}
_BOOLOP_SWAP = {ast.And: ast.Or, ast.Or: ast.And}


@dataclasses.dataclass
class Mutant:
    operator: str
    relative_path: str
    lineno: int
    description: str
    source: str

    def key(self) -> str:
        return f"{self.operator}@{self.relative_path}:{self.lineno}"


class _Mutator(ast.NodeTransformer):
    """Applies exactly one mutation, identified by (node id, operator)."""

    def __init__(self, target_id: int, operator: str) -> None:
        self.target_id = target_id
        self.operator = operator
        self.applied = False

    def _hit(self, node: ast.AST) -> bool:
        return id(node) == self.target_id

    def visit_Compare(self, node: ast.Compare) -> ast.AST:
        self.generic_visit(node)
        if self._hit(node) and self.operator == "flip_comparison":
            new = type(node.ops[0])
            flipped = _CMP_FLIP.get(new)
            if flipped is not None:
                node.ops[0] = flipped()
                self.applied = True
        return node

    def visit_Constant(self, node: ast.Constant) -> ast.AST:
        if not self._hit(node):
            return node
        if self.operator == "flip_bool" and isinstance(node.value, bool):
            node.value = not node.value
            self.applied = True
        elif self.operator == "perturb_number" and isinstance(node.value, (int, float)) \
                and not isinstance(node.value, bool):
            node.value = node.value + 1
            self.applied = True
        elif self.operator == "perturb_string" and isinstance(node.value, str):
            node.value = node.value + "_vacuity_probe"
            self.applied = True
        return node

    def visit_BinOp(self, node: ast.BinOp) -> ast.AST:
        self.generic_visit(node)
        if self._hit(node) and self.operator == "swap_arithmetic":
            swapped = _BINOP_SWAP.get(type(node.op))
            if swapped is not None:
                node.op = swapped()
                self.applied = True
        return node

    def visit_BoolOp(self, node: ast.BoolOp) -> ast.AST:
        self.generic_visit(node)
        if self._hit(node) and self.operator == "swap_boolop":
            swapped = _BOOLOP_SWAP.get(type(node.op))
            if swapped is not None:
                node.op = swapped()
                self.applied = True
        return node

    def visit_Return(self, node: ast.Return) -> ast.AST:
        self.generic_visit(node)
        if self._hit(node) and self.operator == "blank_return" and node.value is not None:
            node.value = ast.Constant(value=None)
            self.applied = True
        return node


def _message_string_nodes(tree: ast.AST) -> set[int]:
    """String constants used as exception or logging messages.

    Changing the text of a ValueError is not a change in behaviour that any
    reasonable check is expected to notice, so such a mutant survives every
    honest suite. Measured on ``examples/demo_project``: the single string in
    ``pricing.py`` is a ValueError message, and leaving it in the pool was
    enough on its own to mark a correct value-checking suite as failing.
    Equivalent mutants do not measure the check; they measure the operator.
    """
    out: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Raise):
            for child in ast.walk(node):
                if isinstance(child, ast.Constant) and isinstance(child.value, str):
                    out.add(id(child))
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) \
                and node.func.attr in {"debug", "info", "warning", "error",
                                       "exception", "critical", "log"}:
            for arg in node.args:
                if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                    out.add(id(arg))
    return out


def _docstring_nodes(tree: ast.AST) -> set[int]:
    """Constants that are docstrings.

    Mutating a docstring changes no behaviour, so no check can kill it. Left in
    the pool it would survive every campaign and brand honest checks VACUOUS --
    the mirror image of the inflated kill rate this tool exists to catch.
    """
    out: set[int] = set()
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            continue
        body = getattr(node, "body", None)
        if not body:
            continue
        first = body[0]
        if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant) \
                and isinstance(first.value.value, str):
            out.add(id(first.value))
    return out


def _candidates(tree: ast.AST) -> list[tuple[ast.AST, str, str]]:
    out: list[tuple[ast.AST, str, str]] = []
    excluded = _docstring_nodes(tree) | _message_string_nodes(tree)
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and id(node) in excluded:
            continue
        if isinstance(node, ast.Compare) and type(node.ops[0]) in _CMP_FLIP:
            out.append((node, "flip_comparison",
                        f"invert `{type(node.ops[0]).__name__}` comparison"))
        elif isinstance(node, ast.Constant):
            if isinstance(node.value, bool):
                out.append((node, "flip_bool", f"{node.value} -> {not node.value}"))
            elif isinstance(node.value, (int, float)):
                out.append((node, "perturb_number", f"{node.value!r} -> {node.value + 1!r}"))
            elif isinstance(node.value, str) and node.value:
                out.append((node, "perturb_string", "append a marker to a string literal"))
        elif isinstance(node, ast.BinOp) and type(node.op) in _BINOP_SWAP:
            out.append((node, "swap_arithmetic", f"swap `{type(node.op).__name__}`"))
        elif isinstance(node, ast.BoolOp) and type(node.op) in _BOOLOP_SWAP:
            out.append((node, "swap_boolop", f"swap `{type(node.op).__name__}`"))
        elif isinstance(node, ast.Return) and node.value is not None:
            out.append((node, "blank_return", "return None instead of the computed value"))
    return out


def _in_region(node: ast.AST, lines: tuple[int, int] | None) -> bool:
    if lines is None:
        return True
    lineno = getattr(node, "lineno", None)
    return lineno is not None and lines[0] <= lineno <= lines[1]


def generate(path: Path, relative_path: str, lines: tuple[int, int] | None = None,
             limit: int | None = None) -> list[Mutant]:
    """Produce distinct, syntactically valid mutants of one file.

    ``lines`` narrows generation to the region a claim actually names, so a
    claim about one function is not credited with killing a mutant somewhere
    else in the file.
    """
    original = Path(path).read_text(encoding="utf-8")
    tree = ast.parse(original)
    mutants: list[Mutant] = []
    seen: set[str] = set()

    for node, operator, description in _candidates(tree):
        if not _in_region(node, lines):
            continue
        fresh = ast.parse(original)
        # locate the same node in the fresh tree by position and type
        twin = _find_twin(fresh, node, operator)
        if twin is None:
            continue
        mutator = _Mutator(id(twin), operator)
        mutated_tree = mutator.visit(fresh)
        if not mutator.applied:
            continue
        ast.fix_missing_locations(mutated_tree)
        try:
            mutated_source = ast.unparse(mutated_tree)
        except Exception:  # pragma: no cover - unparse is total in practice
            continue
        if mutated_source == ast.unparse(ast.parse(original)):
            continue  # the "mutation" changed nothing
        mutant = Mutant(operator=operator, relative_path=relative_path,
                        lineno=getattr(node, "lineno", 0), description=description,
                        source=mutated_source)
        if mutant.key() in seen:
            continue
        seen.add(mutant.key())
        mutants.append(mutant)
        if limit is not None and len(mutants) >= limit:
            break
    return mutants


def _find_twin(fresh_tree: ast.AST, node: ast.AST, operator: str) -> ast.AST | None:
    want = (type(node), getattr(node, "lineno", None), getattr(node, "col_offset", None))
    for candidate in ast.walk(fresh_tree):
        if (type(candidate), getattr(candidate, "lineno", None),
                getattr(candidate, "col_offset", None)) == want:
            return candidate
    return None
